### ISSUE TITLE
Handle loses mouse as edge gets further away from other side

### ISSUE THREAD

**Issue by d4hines** [bokuweb/re-resizable#537]
### Overview of the problem

I'm using re-resizable **version** [6.1.0]   
   

My **browser** is:   Chrome 77
   
I am sure this issue is **not a duplicate**?
It may be a duplicate of https://github.com/bokuweb/re-resizable/issues/257, but I can't quite tell.

### Description

The resize handle tracks less and less with the mouse in an apparent logarithmic fashion the further it gets from the other side.
![re-resizable-bug](https://user-images.githubusercontent.com/25231383/67293591-a0c2fc80-f4b2-11e9-9cb6-8faa2eb7e7d9.gif)

I'm using flexbox to create two divs in a box, and I want to have a draggable handle to adjust the proportion between the two divs. If there is a better way to do this that side-steps the issue I'm having, let me know! I'm by no means a CSS expert.

### Steps to Reproduce
My project is on StackBlitz:
https://stackblitz.com/edit/window-tree-ssdoso?file=ui/branch.jsx
Try resizing any of the drag handles there. 

### Expected behavior
The handle should track with the cursor, no matter how far away it is from the other edge.
### Actual behavior
See GIF

Thanks a ton for this library - it's awesome!

**Comment by afcjunior** [comment]
Just bumping this. The lib is great aside from this <3

**Comment by gustavoFreireS** [comment]
I've identified the issue happens when the sum of children widths are equal to parent's width, I made a gif to show these logs
![2019-11-28 10 32 54](https://user-images.githubusercontent.com/8769796/69810572-fafa6000-11ca-11ea-9c34-61120d732108.gif)

another thing that I notice is that if I put resize ratio equals to parent size the element properly snaps to the other side (but instantly, which is not ideal at all), taking this in consideration, a possible solution that I could see is changing the resize ratio based on the current width of the children being resized and the parent width (on a exponential fashion since it will increase ratio until it reaches the parent size)

**Comment by bokuweb** [comment]
Fixed by @gustavoFreireS

**Comment by bokuweb** [comment]
@d4hines @afcjunior @gustavoFreireS  v6.1.1 published :tada:
